"""Epistemic honesty layer — every research run emits a synthetic-data notice."""

from __future__ import annotations

from pathlib import Path
from typing import Optional

from pydantic import BaseModel


class SyntheticDataNotice(BaseModel):
    """Workflow guide (not legal boilerplate) for synthetic research output."""

    research_question: str
    validation_questions: list[str]

    def render(self) -> str:
        vqs = "\n".join(f"  {i+1}. {q}" for i, q in enumerate(self.validation_questions))
        return f"""# ⚠️ Synthetic Data Notice

## What this is
This research output was generated by a language model simulating user behavior.
The personas, quotes, and behavioral patterns are **synthetic** — produced from
statistical patterns in training data, not observed human behavior.

## What this is NOT
- Real user interviews or usability studies
- Statistically validated market research
- A substitute for talking to actual users

## Your research question
> {self.research_question}

## Validate with real users — ask these 3 questions
{vqs}

## How to use this output
Treat every finding as a **hypothesis to test**, not a conclusion.
Use this output to:
- Decide which user segments to recruit for real interviews
- Prioritize which assumptions carry the most risk if wrong
- Draft interview guides anchored to the findings here

The fastest path to confidence: schedule 3 real user calls this week.
"""


def generate_notice(
    research_question: str,
    validation_questions: Optional[list[str]] = None,
) -> SyntheticDataNotice:
    """Generate a synthetic data notice for a research session."""
    if validation_questions is None:
        validation_questions = [
            f"Can you walk me through the last time you experienced [the problem this research is about]?",
            "What did you try before? Why didn't it stick?",
            "If this tool existed and worked perfectly, what would you be able to do that you can't today?",
        ]
    return SyntheticDataNotice(
        research_question=research_question,
        validation_questions=validation_questions,
    )


def write_notice(notice: SyntheticDataNotice, directory: Path) -> Path:
    """Write SYNTHETIC-DATA-NOTICE.md to the given directory."""
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / "SYNTHETIC-DATA-NOTICE.md"
    path.write_text(notice.render())
    return path
