"""ResearchSession: central state accumulator for the full 4-stage research pipeline."""

from __future__ import annotations

import hashlib
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import yaml
from pydantic import BaseModel, Field

from voice_of_agents.research.notice import generate_notice, write_notice
from voice_of_agents.research.models import (
    JourneyRedesignOutput,
    PersonaResearchOutput,
    ProductResearchInput,
    ProductResearchOutput,
    WorkflowResearchOutput,
)


class ResearchSession(BaseModel):
    """Central state object for the full 4-stage research pipeline.

    Inputs are declared upfront. Outputs accumulate stage-by-stage.
    Serializes to YAML for git-friendly persistence. Each write is safe
    to call after any stage completes — the file is always a complete snapshot.
    """

    # ── Identity ──────────────────────────────────────────────────────
    session_id: str
    slug: str
    created_at: str
    schema_version: str = "1.0"

    # ── Stage 1 input (declared at session creation) ───────────────────
    product_research_input: ProductResearchInput

    # ── Stage outputs (populated as stages complete) ──────────────────
    product_research_output: Optional[ProductResearchOutput] = None
    persona_research_output: Optional[PersonaResearchOutput] = None
    workflow_research_output: Optional[WorkflowResearchOutput] = None
    journey_redesign_output: Optional[JourneyRedesignOutput] = None

    # ── Run metadata ──────────────────────────────────────────────────
    stages_completed: list[str] = Field(default_factory=list)
    error_log: list[str] = Field(default_factory=list)

    @classmethod
    def create(
        cls,
        product_research_input: ProductResearchInput,
        **kwargs,
    ) -> "ResearchSession":
        now = datetime.now(timezone.utc)
        slug = product_research_input.slug
        session_id = hashlib.sha256(f"{slug}-{now.isoformat()}".encode()).hexdigest()[:12]
        return cls(
            session_id=session_id,
            slug=slug,
            created_at=now.strftime("%Y-%m-%d"),
            product_research_input=product_research_input,
            **kwargs,
        )

    def is_stage_complete(self, stage: str) -> bool:
        return stage in self.stages_completed

    def mark_stage_complete(self, stage: str) -> None:
        if stage not in self.stages_completed:
            self.stages_completed.append(stage)

    def log_error(self, stage: str, message: str) -> None:
        self.error_log.append(f"[{stage}] {message}")

    # ── Persistence ───────────────────────────────────────────────────

    def to_yaml(self) -> str:
        return yaml.dump(
            self.model_dump(mode="json", exclude_none=True),
            default_flow_style=False,
            allow_unicode=True,
            sort_keys=False,
        )

    def save(self, path: Path) -> None:
        """Write current session state to YAML. Safe to call after each stage."""
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.to_yaml())
        notice = generate_notice(self.product_research_input.question)
        write_notice(notice, path.parent)

    @classmethod
    def load(cls, path: Path) -> "ResearchSession":
        data = yaml.safe_load(path.read_text())
        return cls(**data)

    # ── Claude Code summary artifact ───────────────────────────────────

    def export_summary(self, path: Optional[Path] = None) -> str:
        """Emit a RESEARCH-SUMMARY.md artifact for Claude Code submodule use.

        This structured markdown file is what Claude Code reads when this library
        is installed as a git submodule to understand the research context.
        """
        notice = generate_notice(self.product_research_input.question)
        lines = [
            f"# Research Session: {self.slug}",
            "",
            "> ⚠️ **Synthetic Data** — treat every finding as a hypothesis to validate with real users.",
            "> This output was generated by a language model, not observed from real user behavior.",
            "",
            f"**Session ID:** `{self.session_id}` | **Date:** {self.created_at} | **Schema:** v{self.schema_version}",
            "",
            "## Research Question",
            "",
            self.product_research_input.question,
            "",
            f"**Scope:** {self.product_research_input.scope}",
            "",
        ]

        if self.product_research_output:
            out = self.product_research_output
            lines += [
                "## Stage 1 Complete: Product Research",
                "",
                f"- Hypotheses: {len(out.hypotheses)} ({', '.join(h.id for h in out.hypotheses)})",
                f"- Subjects interviewed: {len(out.subjects)}",
                f"- Segments identified: {len(out.segments)}",
            ]
            if out.all_hypotheses_supported_flag:
                lines.append(
                    "- **WARNING:** All hypotheses returned `supports` — "
                    "high confirmation-bias risk. Review sampling frame before proceeding."
                )
            lines.append("")

        if self.persona_research_output:
            out = self.persona_research_output
            lines += [
                "## Stage 2 Complete: Personas from Research",
                "",
                f"- Personas synthesized: {len(out.persona_sidecars)}",
                f"- UXW IDs: {', '.join(p.uxw_id for p in out.persona_sidecars)}",
                f"- Top-up subjects added: {len(out.topup_subjects)}",
                "",
            ]

        if self.workflow_research_output:
            out = self.workflow_research_output
            lines += [
                "## Stage 3 Complete: Workflows from Interviews",
                "",
                f"- Persona: {out.uxw_id}",
                f"- Episodes: {len(out.episodes)}",
                f"- Workflow maps emitted: {len(out.workflow_maps)}",
                "",
            ]

        if self.journey_redesign_output:
            out = self.journey_redesign_output
            lines += [
                "## Stage 4 Complete: Journey Redesign",
                "",
                f"- Average focus group score: {out.average_score:.1f}/10",
                f"- Cross-cutting must-fixes: {len(out.cross_cutting_must_fixes)}",
                f"- Plan emitted: `{out.plan_dir}`",
                "",
            ]

        lines += [
            "## Stages Completed",
            "",
            (", ".join(self.stages_completed) if self.stages_completed else "none"),
            "",
            "## How to Use in Claude Code",
            "",
            "```python",
            "from voice_of_agents.research.session import ResearchSession",
            "from pathlib import Path",
            f'session = ResearchSession.load(Path("research-sessions/{self.slug}.yaml"))',
            "",
            "# Access typed outputs",
            "session.product_research_output.segments",
            "session.persona_research_output.persona_sidecars",
            "session.workflow_research_output.workflow_maps",
            "```",
            "",
            "## How to Resume a Partial Run",
            "",
            "```bash",
            f"voa research run research-config.yaml --session research-sessions/{self.slug}.yaml",
            "```",
        ]

        if self.error_log:
            lines += [
                "",
                "## Errors",
                "",
                *[f"- {e}" for e in self.error_log],
            ]

        lines += [
            "",
            "---",
            "",
            notice.render(),
        ]

        content = "\n".join(lines)
        if path:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            write_notice(notice, path.parent)
        return content
